### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by augustobr1to** [imsnif/monocle#5]
I'm trying to install the Monocle plugin but I'm getting this error...

![image](https://github.com/imsnif/monocle/assets/7965922/f93ffc46-d8f2-401e-90ac-ddbec566bb2e)

**Comment by dit7ya** [comment]
I can also reproduce this.

**Comment by imsnif** [comment]
I am embarrassed to say I did not yet get a chance to update this to the new Zellij version, which has some breaking changes for plugins :/

If someone would like to do the work in the [upgrade guide](https://zellij.dev/documentation/plugin-upgrade-0.38.0) (and also likely update some function signatures), I'd be happy to accept a PR here.

Otherwise, I'm going on vacation tomorrow - so will take care of this mid-september when I get back. Sorry for the inconvenience!

**Comment by LFd3v** [comment]
@imsnif Bump,please check #6. Thank you.
